# -*- coding: utf-8 -*-
"""Configuración de Firebase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xl26CkVs9ySNwpkC3jczW6ie9n0i364A
"""

import streamlit as st
import firebase_admin
from firebase_admin import credentials

def init_firebase():
    """
    Initializes the Firebase Admin SDK using credentials from Streamlit secrets.
    Uses @st.cache_resource to ensure it only runs once.
    """
    @st.cache_resource
    def init_app():
        # Get the credentials from Streamlit's secrets
        firebase_credentials = {
            "type": st.secrets["firebase"]["type"],
            "project_id": st.secrets["firebase"]["project_id"],
            "private_key_id": st.secrets["firebase"]["private_key_id"],
            "private_key": st.secrets["firebase"]["private_key"].replace('\\n', '\n'),
            "client_email": st.secrets["firebase"]["client_email"],
            "client_id": st.secrets["firebase"]["client_id"],
            "auth_uri": st.secrets["firebase"]["auth_uri"],
            "token_uri": st.secrets["firebase"]["token_uri"],
            "auth_provider_x509_cert_url": st.secrets["firebase"]["auth_provider_x509_cert_url"],
            "client_x509_cert_url": st.secrets["firebase"]["client_x509_cert_url"],
        }

        cred = credentials.Certificate(firebase_credentials)

        # Check if the app is already initialized
        if not firebase_admin._apps:
            firebase_admin.initialize_app(cred)

        return firebase_admin.firestore.client()

    return init_app()